### ISSUE TITLE
go get package fetch fails due to certificates

### ISSUE THREAD

**Issue by quiznilo1** [jda/go-crowd#1]
% go get -u -v go.jona.me/crowd
Fetching https://go.jona.me/crowd?go-get=1
https fetch failed.
import "go.jona.me/crowd": https fetch: Get https://go.jona.me/crowd?go-get=1: x509: certificate is valid for oms.coldshore.com, coldshore.com, not go.jona.me
package go.jona.me/crowd: unrecognized import path "go.jona.me/crowd"

% git config http.sslVerify
false

 % go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/userone/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT=""
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="x86_64-pc-linux-gnu-g++"
CGO_ENABLED="1"

**Comment by jda** [comment]
This should be fixed. I added a SSL certificate for go.jona.me.
